### ISSUE TITLE
No screenshots nor demo app

### ISSUE THREAD

**Issue by MarcinOrlowski** [aercanozcan/Progressive#2]
I'd strongly recommend adding some screenshots and/or demo app so people looking for something like that could easily see how it is going to look when incorporated into their app. For now it's just blind guess so I believe majority just skips your lib.

**Comment by aercanozcan** [comment]
Thank you. I will work on it as soon as i have free time.

**Comment by aercanozcan** [comment]
![screenshot_2016-01-06-08-55-53](https://cloud.githubusercontent.com/assets/2137007/12136806/f9d76818-b453-11e5-94f6-22df8c80f759.png)
![screenshot_2016-01-06-08-56-00](https://cloud.githubusercontent.com/assets/2137007/12136808/fd774dbc-b453-11e5-9e12-493120f5f1c2.png)
